### ISSUE TITLE
Analyze requirements to determine high level system architecture and design

### ISSUE THREAD

**Issue by mcsamuelshoko** [mcsamuelshoko/telko-moment-server#3]

**Comment by mcsamuelshoko** [comment]
- [x] analysis of high-level requirements has been a success and usage of WebSockets has been understood on how to proceed.
-  now we're left with the planning of the architecture

**Comment by ellispax** [comment]
Okay, I think there is a need for a bit more info on what will be the architecture.

**Comment by mcsamuelshoko** [comment]
oh, alright will make sure to add more detail on the planning. had not planned it yet though

**Comment by mcsamuelshoko** [comment]
- [x] finished planning and architecture, more refinements will be added later on
