### ISSUE TITLE
Conduct user interviews to gather feedback on the chat app requirements.

### ISSUE THREAD

**Issue by mcsamuelshoko** [mcsamuelshoko/telko-moment-server#6]

**Comment by ellispax** [comment]
Is there a specific demographic that we can target. With regards to me, I'm not in Zim so I could just interview other people, right?

**Comment by mcsamuelshoko** [comment]
that was an awesome idea,.. unfortunately i missed it,... i guess for now we'll rush in to the prototype/app creation
